--------------------------------------------------------
--  DDL for Table MD_CONSTRAINTS
--------------------------------------------------------

  CREATE TABLE "MD_CONSTRAINTS" ("ID" NUMBER, "DELETE_CLAUSE" VARCHAR2(4000), "NAME" VARCHAR2(4000), "CONSTRAINT_TYPE" VARCHAR2(4000), "TABLE_ID_FK" NUMBER, "REFTABLE_ID_FK" NUMBER, "CONSTRAINT_TEXT" CLOB, "LANGUAGE" VARCHAR2(40), "COMMENTS" VARCHAR2(4000), "SECURITY_GROUP_ID" NUMBER DEFAULT 0, "CREATED_ON" DATE DEFAULT sysdate, "CREATED_BY" VARCHAR2(255), "LAST_UPDATED_ON" DATE, "LAST_UPDATED_BY" VARCHAR2(255)) 

   COMMENT ON COLUMN "MD_CONSTRAINTS"."ID" IS 'Primary Key'
   COMMENT ON COLUMN "MD_CONSTRAINTS"."DELETE_CLAUSE" IS 'delete option , can be either CASCADE, RESTRICT or NULL'
   COMMENT ON COLUMN "MD_CONSTRAINTS"."NAME" IS 'Name of the constraint //OBJECTNAME'
   COMMENT ON COLUMN "MD_CONSTRAINTS"."CONSTRAINT_TYPE" IS 'Type of the constraint (e.g. CHECK)'
   COMMENT ON COLUMN "MD_CONSTRAINTS"."TABLE_ID_FK" IS 'Table on which this constraint exists //PARENTFIELD'
   COMMENT ON COLUMN "MD_CONSTRAINTS"."REFTABLE_ID_FK" IS 'Used in foreign keys - this gives the table that we refer to.'
   COMMENT ON COLUMN "MD_CONSTRAINTS"."CONSTRAINT_TEXT" IS 'The text of the constraint'
   COMMENT ON COLUMN "MD_CONSTRAINTS"."LANGUAGE" IS '//PUBLIC'
   COMMENT ON TABLE "MD_CONSTRAINTS"  IS 'Table for storing information about a constraint'
/
