--------------------------------------------------------
--  DDL for Table MD_FILE_ARTIFACTS
--------------------------------------------------------

  CREATE TABLE "MD_FILE_ARTIFACTS" ("ID" NUMBER, "APPLICATIONFILES_ID" NUMBER, "PATTERN" VARCHAR2(4000), "STRING_FOUND" VARCHAR2(4000), "STRING_REPLACED" VARCHAR2(4000), "TYPE" VARCHAR2(200), "STATUS" VARCHAR2(4000), "LINE" NUMBER, "PATTERN_START" NUMBER, "PATTERN_END" NUMBER, "DUE_DATE" DATE, "DB_TYPE" VARCHAR2(100), "CODE_TYPE" VARCHAR2(1000), "DESCRIPTION" VARCHAR2(4000), "PRIORITY" NUMBER(*,0), "SECURITY_GROUP_ID" VARCHAR2(20) DEFAULT '0', "CREATED_ON" DATE DEFAULT sysdate, "CREATED_BY" VARCHAR2(4000), "LAST_UPDATED" DATE, "LAST_UPDATED_BY" VARCHAR2(4000)) 

   COMMENT ON COLUMN "MD_FILE_ARTIFACTS"."PATTERN" IS 'Pattern used to search source file for interesting artifiacts'
   COMMENT ON COLUMN "MD_FILE_ARTIFACTS"."STRING_FOUND" IS 'String found in source from the pattern supplied'
   COMMENT ON COLUMN "MD_FILE_ARTIFACTS"."STRING_REPLACED" IS 'This is the string which replace the string found if it was replaced.'
   COMMENT ON COLUMN "MD_FILE_ARTIFACTS"."TYPE" IS 'This is the type of the replacement.  It could be a straight replace from a replacement pattern, or we could have passed the string to a translator which would change the string depending on the database.'
   COMMENT ON COLUMN "MD_FILE_ARTIFACTS"."STATUS" IS 'Pattern used to search source file for interesting artifiacts'
   COMMENT ON COLUMN "MD_FILE_ARTIFACTS"."DUE_DATE" IS 'Due date is used by the TODO mechanism to manage the validation and work to complete this change'
   COMMENT ON COLUMN "MD_FILE_ARTIFACTS"."DB_TYPE" IS 'Source database calls type'
   COMMENT ON COLUMN "MD_FILE_ARTIFACTS"."CODE_TYPE" IS 'Source code db api, like dblib, jdbc'
   COMMENT ON COLUMN "MD_FILE_ARTIFACTS"."DESCRIPTION" IS 'This is a description of the artifact which will have a default generated by the scanner and then can be modified by the user to be more appropriate for their use'
   COMMENT ON COLUMN "MD_FILE_ARTIFACTS"."PRIORITY" IS 'The priority is set for the TODOs so they can be managed by the user'
   COMMENT ON TABLE "MD_FILE_ARTIFACTS"  IS 'Holds a tuple for each interesting thing the scanner finds in a file'
/
