--------------------------------------------------------
--  DDL for Table MD_MIGR_PARAMETER
--------------------------------------------------------

  CREATE TABLE "MD_MIGR_PARAMETER" ("ID" NUMBER, "CONNECTION_ID_FK" NUMBER, "OBJECT_ID" NUMBER, "OBJECT_TYPE" VARCHAR2(4000), "PARAM_EXISTING" NUMBER, "PARAM_ORDER" NUMBER, "PARAM_NAME" VARCHAR2(4000), "PARAM_TYPE" VARCHAR2(4000), "PARAM_DATA_TYPE" VARCHAR2(4000), "PERCISION" NUMBER, "SCALE" NUMBER, "NULLABLE" CHAR(1), "DEFAULT_VALUE" VARCHAR2(4000), "SECURITY_GROUP_ID" NUMBER DEFAULT 0, "CREATED_ON" DATE DEFAULT sysdate, "CREATED_BY" VARCHAR2(255), "LAST_UPDATED_ON" DATE, "LAST_UPDATED_BY" VARCHAR2(255)) 

   COMMENT ON COLUMN "MD_MIGR_PARAMETER"."CONNECTION_ID_FK" IS 'the connection in which this belongs //PARENTFIELD'
   COMMENT ON COLUMN "MD_MIGR_PARAMETER"."PARAM_EXISTING" IS '1 represents a new parameter for PL/SQL that was not present in the origional. 0 represents a n existing parameter that was present in the origional'
   COMMENT ON COLUMN "MD_MIGR_PARAMETER"."PARAM_ORDER" IS 'IF -1 THEN THIS PARAM IS A RETURN PARAMETER. 1 WILL BE THE FIRST PARAMETER IN THE PARAMETER LIST'
/
